development: &default
  adapter: postgresql
  database: revolvo_development
  host: localhost
  user: djcp
  pool: 5
  timeout: 5000

test: &test
  <<: *default
  database: revolvo_test
  min_messages: warning

cucumber:
  <<: *test
